mayshukla/ece493-capstone

src/frontend/js/clienttoserverconnection.js
src/frontend/js/main.js
src/gameserver.py
src/server.py

Created ClientToServerConnection and ServerToClientConnection classes to manage websocket communications.
Created GameServer class to manage the matchmaking queue. When two players join the queue, GameServer.start_game() is called (start_game doesn't do anything yet).

Implement websocket connection and queue

---

.github/workflows/ci.yaml
README.md
src/message.py
test/test_message.py

This class can convert itself to and from json. The idea is that it can be used to send messages between the server and client in a standard json format. So far I've only declared two message types but we'll need to declare more as we go.
I also added python unittests and a github workflow to run these unittests on pushes and pull requests.

Create Message class in python

---

src/agent.py
src/agent_state.py
src/frontend/js/clienttoserverconnection.js
src/frontend/js/gameSetup.js
src/frontend/js/message.js
src/game.py
src/physics_engine.py
src/projectile_state.py
src/server.py
src/vector2.py
test/test_game.py
test/test_message.py
test/test_physics.py
test/test_vector2.py

Game tick() now sends projectile and agent states to every client on each call.
Added state message handling to the frontend to set the agents position. The client message handling for all message types still need work.
Added an angle property to the agent state and projectile state messages. Added some helper functions to Vector2 to accomplish this. The angles sent to clients are all in degrees not radians.
Updated the collision callback so that the two collided object_states are passed to the callback.
Added callback methods to Agent for the player to override.
Added a scan_area method to the PhysicsEngine class. Updated the main game loop so that each agent scans their vicinity on each loop. Agent.on_enemy_scanned() and Agent.on_obstacle_scanned() will be invoked based on what the …

Game state update

---

src/agent.py
src/game.py
src/physics_engine.py
test/test_agent.py
test/test_game.py
test/test_physics.py

This implements set_movement_speed and set_movement_direction.
I just chose the value of MAX_SPEED arbitrarily. We can adjust this later if we want.

Implement movement API

---

src/agent.py
src/game.py
src/physics_engine.py
src/vector2.py
test/test_game.py

#19 should be merged first. Use this link to see the changes in just this branch: <https://github.com/mayshukla/ece493-capstone/compare/movement-api..attack-api>
This implements attack_ranged.
Notes on attack cooldown:
- There is a cooldown period for attacks defined by Agent.ATTACK_COOLDOWN_MAX
- During the cooldown time, agents cannot attack again
- During the cooldown time, the max speed is reduced to Agent.MAX_SPEED_DURING_ATTACK
Let me know if this cooldown logic makes sense or needs to be changed.

Implement attack API

---

src/game.py

Add projectiles to a list in game,py as they are created and remove them as they are destroyed. The projectiles in the list are then sent to the clients in messages.

keep list of projectiles updates to send messages to clients

---

src/agent.py
src/game.py

The _clip_velocity method was being called after run and collision callbacks, but before the scan callbacks. Added additional calls to it after scan callbacks.

call _clip_velocity after scan callbacks

---

src/physics_engine.py

Don't set velocities to zero when projectile collides with agent

---

src/agent.py
src/agent_state.py
src/dynamic_object_state.py
src/frontend/index.html
src/frontend/js/clienttoserverconnection.js
src/frontend/js/gameSetup.js
src/frontend/js/main.js
src/frontend/js/message.js
src/frontend/js/renderer.js
src/game.py
src/gameserver.py
src/globals.py
src/message.py
src/object_state.py
src/obstacle.py
src/physics_engine.py
src/projectile_state.py
src/server.py
src/vector2.py

Added a comment block to the top of each file which references the relevant functional requirements for that file.
I basically just listed the requirements without going into further detail. I can add more detail if needed, but I think this is all we need.

added comments with references to requirements

---

src/agent.py
src/agent_state.py
src/frontend/index.html
test/test_agent.py

Fixes issue #45 
Added an angle field to agent_state and made appropriate changes to agent methods.
Also changed the title from "ECE 493 CAPSTONE PROJECT" to "CODE TO KILL".

added angle field to agent_state

---

.github/workflows/ci.yaml
.gitignore
README.md
test/requirements.txt
test/test_frontend.py

This implements 2 of the 3 end-to-end tests we want.
It also works in github actions!

Write end-to-end tests for error during code submission and error during game

---

src/frontend/js/clienttoserverconnection.js
src/frontend/js/gameSetup.js

Closes #50 
Agent flashes green when attacking and flashes red when damaged.

Implement attack and damage animations

---

src/game.py
src/physics_engine.py

physics engine doesn't process collisions if the object id is none

---

src/agent.py
src/game.py
src/physics_engine.py

Adds more if statements to prevent "None type has no method", "element not in list", or "key not in dict" errors.
Would it be more appropriate to let these errors be raised for debugging? At least the unit tests run without any errors now.

added if statements to prevent raising errors

---

src/physics_engine.py
test/test_game.py

This makes the obstacles one single shape so that they don't generate multiple collisions

Use Poly shape for obstacles

---

src/server.py

This can also be fixed by editing the windows registry but I would rather not rely on markers to do that

Add fix for weird mimetype behaviour on windows

---

src/frontend/js/gameSetup.js
src/game.py

Fixes #60 
Note that Pixi uses the top left of a sprite as it's position by default. The Obstacle class uses the center of the obstacle.

Make obstacle positions consistent between frontend and backend

---

src/agent.py
test/agent_code/agent3.py
test/test_agent.py
test/test_frontend.py

Added a frontend end test that tests for a tie result and covers the remaining API methods that are not used in test_completed_game.
Also fixed a bug in get_agents_health. test_get_agents_health was only passing because the test was mocked incorrectly.
Fixes issue #62. Closes issue #23.

Frontend tests

---

Procfile
requirements.txt
setup.py
src/server.py

I needed to add this stuff in order for heroku to recognize this as a python project and install pip dependencies.

Add boilerplate so it runs on heroku

---

test/test_game.py

Just extended the test_tick test so that it verifies that the expected methods are called.

extended test_tick
